name: lulab
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.1
  flutter_swiper_null_safety: ^1.0.2
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  graphql_flutter: ^5.0.0
  chewie: ^1.2.2
  video_player: ^2.2.7
  get: ^4.5.1
  fluttertoast: ^8.0.8
  #flutter_sound: ^8.2.5
  device_info: ^2.0.3
  #fluwx: ^3.6.1+4
  fbutton_nullsafety: ^5.0.0
  #flutter_webview_plugin: ^0.4.0
  #flutter_ffmpeg: ^0.4.2
  #flutter_sound_lite: ^8.2.5
  url_launcher: ^6.0.17
  fluro: ^2.0.3
  #flutter_html: ^2.2.1
  #permission_handler: ^8.1.3 #请求录音权限
  audioplayers: ^0.20.1
  text_to_speech: ^0.2.3
  flutter_tts: ^3.3.2
  path_provider: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  uses-material-design: true

  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/icons/iconfont.ttf

    - family: MyFontStyle
      fonts:
        - asset: assets/fonts/汉仪行楷简.ttf
