name: proflu
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.1
  flutter_swiper_null_safety: ^1.0.2
  #dio: ^4.0.0
  shared_preferences: ^2.0.7
  graphql_flutter: ^5.0.0
  chewie: ^1.2.2
  video_player: ^2.2.7
  get: ^4.5.1
  fluttertoast: ^8.0.8
  #flutter_sound: ^8.2.5
  #fluwx: ^3.6.1+4
  fbutton_nullsafety: ^5.0.0
  #flutter_webview_plugin: ^0.4.0
  #flutter_ffmpeg: ^0.4.2
  #flutter_sound_lite: ^8.2.5
  #fluro: ^2.0.3
  #flutter_html: ^2.2.1
  #permission_handler: ^8.1.3 #请求录音权限
  audioplayers: ^0.20.1
  text_to_speech: ^0.2.3
  speech_to_text: ^5.4.2
  flutter_tts: ^3.3.2
  path_provider: ^2.0.9
  flutter_easyrefresh: ^2.2.1
  avatar_glow: ^2.0.2 #用于按钮周围的发光效果
  permission_handler: ^8.3.0
  sound_stream: ^0.3.0
  flutter_echart: ^1.0.0
  charts_flutter: ^0.12.0
  zefyrka: ^1.1.1
  dio_cookie_manager: ^2.0.0
  image_picker: ^0.8.4+11
  fijkplayer: ^0.10.1
  add_2_calendar: ^2.1.2
  #xfspeech: ^1.0.0
  date_format: ^2.0.5
  alarm_calendar: ^0.0.5
  share_plus: ^3.1.0
  image_preview: ^1.0.1
  #flutter_echarts: ^1.3.5
  flutter_spinkit: ^5.1.0
  webview_flutter: ^3.0.1
  flutter_markdown: ^0.6.9
  any_syntax_highlighter: ^0.0.12
  porcupine_flutter: ^2.1.1
  flutter_picker: ^2.0.1
  flutter_custom_dialog: ^1.2.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  url_launcher: ^6.0.20
  device_info_plus: ^3.2.3

  flutter_localizations:
    sdk: flutter
  readmore: ^2.1.0
  keyboard_dismisser: ^2.0.1
  extended_text: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
    - assets/test_service_account.json
    - assets/ppn/first_android.ppn
    - assets/ppn/second_android.ppn
    - assets/ppn/three_android.ppn
    - assets/animation/

  uses-material-design: true

  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/icons/iconfont.ttf

    - family: MyFontStyle2
      fonts:
        - asset: assets/fonts/汉仪行楷简.ttf

    - family: MyFontStyle
      fonts:
        - asset: assets/fonts/汉仪尚魏手书体（英文字体）.ttf
